# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: macp/modes/handoff/v1/handoff.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'macp/modes/handoff/v1/handoff.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#macp/modes/handoff/v1/handoff.proto\x12\x15macp.modes.handoff.v1\"d\n\x13HandoffOfferPayload\x12\x12\n\nhandoff_id\x18\x01 \x01(\t\x12\x1a\n\x12target_participant\x18\x02 \x01(\t\x12\r\n\x05scope\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t\"R\n\x15HandoffContextPayload\x12\x12\n\nhandoff_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\x0c\"O\n\x14HandoffAcceptPayload\x12\x12\n\nhandoff_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65pted_by\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\"P\n\x15HandoffDeclinePayload\x12\x12\n\nhandoff_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65\x63lined_by\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'macp.modes.handoff.v1.handoff_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HANDOFFOFFERPAYLOAD']._serialized_start=62
  _globals['_HANDOFFOFFERPAYLOAD']._serialized_end=162
  _globals['_HANDOFFCONTEXTPAYLOAD']._serialized_start=164
  _globals['_HANDOFFCONTEXTPAYLOAD']._serialized_end=246
  _globals['_HANDOFFACCEPTPAYLOAD']._serialized_start=248
  _globals['_HANDOFFACCEPTPAYLOAD']._serialized_end=327
  _globals['_HANDOFFDECLINEPAYLOAD']._serialized_start=329
  _globals['_HANDOFFDECLINEPAYLOAD']._serialized_end=409
# @@protoc_insertion_point(module_scope)
