# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: macp/modes/proposal/v1/proposal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'macp/modes/proposal/v1/proposal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%macp/modes/proposal/v1/proposal.proto\x12\x16macp.modes.proposal.v1\"e\n\x0fProposalPayload\x12\x13\n\x0bproposal_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x04 \x01(\x0c\x12\x0c\n\x04tags\x18\x05 \x03(\t\"~\n\x16\x43ounterProposalPayload\x12\x13\n\x0bproposal_id\x18\x01 \x01(\t\x12\x1e\n\x16supersedes_proposal_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07summary\x18\x04 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x05 \x01(\x0c\"4\n\rAcceptPayload\x12\x13\n\x0bproposal_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"F\n\rRejectPayload\x12\x13\n\x0bproposal_id\x18\x01 \x01(\t\x12\x10\n\x08terminal\x18\x02 \x01(\x08\x12\x0e\n\x06reason\x18\x03 \x01(\t\"6\n\x0fWithdrawPayload\x12\x13\n\x0bproposal_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'macp.modes.proposal.v1.proposal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROPOSALPAYLOAD']._serialized_start=65
  _globals['_PROPOSALPAYLOAD']._serialized_end=166
  _globals['_COUNTERPROPOSALPAYLOAD']._serialized_start=168
  _globals['_COUNTERPROPOSALPAYLOAD']._serialized_end=294
  _globals['_ACCEPTPAYLOAD']._serialized_start=296
  _globals['_ACCEPTPAYLOAD']._serialized_end=348
  _globals['_REJECTPAYLOAD']._serialized_start=350
  _globals['_REJECTPAYLOAD']._serialized_end=420
  _globals['_WITHDRAWPAYLOAD']._serialized_start=422
  _globals['_WITHDRAWPAYLOAD']._serialized_end=476
# @@protoc_insertion_point(module_scope)
