# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: macp/modes/quorum/v1/quorum.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'macp/modes/quorum/v1/quorum.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!macp/modes/quorum/v1/quorum.proto\x12\x14macp.modes.quorum.v1\"z\n\x16\x41pprovalRequestPayload\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x04 \x01(\x0c\x12\x1a\n\x12required_approvals\x18\x05 \x01(\r\"4\n\x0e\x41pprovePayload\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"3\n\rRejectPayload\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"4\n\x0e\x41\x62stainPayload\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'macp.modes.quorum.v1.quorum_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPROVALREQUESTPAYLOAD']._serialized_start=59
  _globals['_APPROVALREQUESTPAYLOAD']._serialized_end=181
  _globals['_APPROVEPAYLOAD']._serialized_start=183
  _globals['_APPROVEPAYLOAD']._serialized_end=235
  _globals['_REJECTPAYLOAD']._serialized_start=237
  _globals['_REJECTPAYLOAD']._serialized_end=288
  _globals['_ABSTAINPAYLOAD']._serialized_start=290
  _globals['_ABSTAINPAYLOAD']._serialized_end=342
# @@protoc_insertion_point(module_scope)
