# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from macp.v1 import core_pb2 as macp_dot_v1_dot_core__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in macp/v1/core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MACPRuntimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/macp.v1.MACPRuntimeService/Initialize',
                request_serializer=macp_dot_v1_dot_core__pb2.InitializeRequest.SerializeToString,
                response_deserializer=macp_dot_v1_dot_core__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.Send = channel.unary_unary(
                '/macp.v1.MACPRuntimeService/Send',
                request_serializer=macp_dot_v1_dot_core__pb2.SendRequest.SerializeToString,
                response_deserializer=macp_dot_v1_dot_core__pb2.SendResponse.FromString,
                _registered_method=True)
        self.StreamSession = channel.stream_stream(
                '/macp.v1.MACPRuntimeService/StreamSession',
                request_serializer=macp_dot_v1_dot_core__pb2.StreamSessionRequest.SerializeToString,
                response_deserializer=macp_dot_v1_dot_core__pb2.StreamSessionResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/macp.v1.MACPRuntimeService/GetSession',
                request_serializer=macp_dot_v1_dot_core__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=macp_dot_v1_dot_core__pb2.GetSessionResponse.FromString,
                _registered_method=True)
        self.CancelSession = channel.unary_unary(
                '/macp.v1.MACPRuntimeService/CancelSession',
                request_serializer=macp_dot_v1_dot_core__pb2.CancelSessionRequest.SerializeToString,
                response_deserializer=macp_dot_v1_dot_core__pb2.CancelSessionResponse.FromString,
                _registered_method=True)
        self.GetManifest = channel.unary_unary(
                '/macp.v1.MACPRuntimeService/GetManifest',
                request_serializer=macp_dot_v1_dot_core__pb2.GetManifestRequest.SerializeToString,
                response_deserializer=macp_dot_v1_dot_core__pb2.GetManifestResponse.FromString,
                _registered_method=True)
        self.ListModes = channel.unary_unary(
                '/macp.v1.MACPRuntimeService/ListModes',
                request_serializer=macp_dot_v1_dot_core__pb2.ListModesRequest.SerializeToString,
                response_deserializer=macp_dot_v1_dot_core__pb2.ListModesResponse.FromString,
                _registered_method=True)
        self.WatchModeRegistry = channel.unary_stream(
                '/macp.v1.MACPRuntimeService/WatchModeRegistry',
                request_serializer=macp_dot_v1_dot_core__pb2.WatchModeRegistryRequest.SerializeToString,
                response_deserializer=macp_dot_v1_dot_core__pb2.WatchModeRegistryResponse.FromString,
                _registered_method=True)
        self.ListRoots = channel.unary_unary(
                '/macp.v1.MACPRuntimeService/ListRoots',
                request_serializer=macp_dot_v1_dot_core__pb2.ListRootsRequest.SerializeToString,
                response_deserializer=macp_dot_v1_dot_core__pb2.ListRootsResponse.FromString,
                _registered_method=True)
        self.WatchRoots = channel.unary_stream(
                '/macp.v1.MACPRuntimeService/WatchRoots',
                request_serializer=macp_dot_v1_dot_core__pb2.WatchRootsRequest.SerializeToString,
                response_deserializer=macp_dot_v1_dot_core__pb2.WatchRootsResponse.FromString,
                _registered_method=True)
        self.ListExtModes = channel.unary_unary(
                '/macp.v1.MACPRuntimeService/ListExtModes',
                request_serializer=macp_dot_v1_dot_core__pb2.ListExtModesRequest.SerializeToString,
                response_deserializer=macp_dot_v1_dot_core__pb2.ListExtModesResponse.FromString,
                _registered_method=True)
        self.RegisterExtMode = channel.unary_unary(
                '/macp.v1.MACPRuntimeService/RegisterExtMode',
                request_serializer=macp_dot_v1_dot_core__pb2.RegisterExtModeRequest.SerializeToString,
                response_deserializer=macp_dot_v1_dot_core__pb2.RegisterExtModeResponse.FromString,
                _registered_method=True)
        self.UnregisterExtMode = channel.unary_unary(
                '/macp.v1.MACPRuntimeService/UnregisterExtMode',
                request_serializer=macp_dot_v1_dot_core__pb2.UnregisterExtModeRequest.SerializeToString,
                response_deserializer=macp_dot_v1_dot_core__pb2.UnregisterExtModeResponse.FromString,
                _registered_method=True)
        self.PromoteMode = channel.unary_unary(
                '/macp.v1.MACPRuntimeService/PromoteMode',
                request_serializer=macp_dot_v1_dot_core__pb2.PromoteModeRequest.SerializeToString,
                response_deserializer=macp_dot_v1_dot_core__pb2.PromoteModeResponse.FromString,
                _registered_method=True)


class MACPRuntimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Initialize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSession(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetManifest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchModeRegistry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRoots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchRoots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExtModes(self, request, context):
        """Extension mode lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterExtMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterExtMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MACPRuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=macp_dot_v1_dot_core__pb2.InitializeRequest.FromString,
                    response_serializer=macp_dot_v1_dot_core__pb2.InitializeResponse.SerializeToString,
            ),
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=macp_dot_v1_dot_core__pb2.SendRequest.FromString,
                    response_serializer=macp_dot_v1_dot_core__pb2.SendResponse.SerializeToString,
            ),
            'StreamSession': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSession,
                    request_deserializer=macp_dot_v1_dot_core__pb2.StreamSessionRequest.FromString,
                    response_serializer=macp_dot_v1_dot_core__pb2.StreamSessionResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=macp_dot_v1_dot_core__pb2.GetSessionRequest.FromString,
                    response_serializer=macp_dot_v1_dot_core__pb2.GetSessionResponse.SerializeToString,
            ),
            'CancelSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelSession,
                    request_deserializer=macp_dot_v1_dot_core__pb2.CancelSessionRequest.FromString,
                    response_serializer=macp_dot_v1_dot_core__pb2.CancelSessionResponse.SerializeToString,
            ),
            'GetManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetManifest,
                    request_deserializer=macp_dot_v1_dot_core__pb2.GetManifestRequest.FromString,
                    response_serializer=macp_dot_v1_dot_core__pb2.GetManifestResponse.SerializeToString,
            ),
            'ListModes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModes,
                    request_deserializer=macp_dot_v1_dot_core__pb2.ListModesRequest.FromString,
                    response_serializer=macp_dot_v1_dot_core__pb2.ListModesResponse.SerializeToString,
            ),
            'WatchModeRegistry': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchModeRegistry,
                    request_deserializer=macp_dot_v1_dot_core__pb2.WatchModeRegistryRequest.FromString,
                    response_serializer=macp_dot_v1_dot_core__pb2.WatchModeRegistryResponse.SerializeToString,
            ),
            'ListRoots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRoots,
                    request_deserializer=macp_dot_v1_dot_core__pb2.ListRootsRequest.FromString,
                    response_serializer=macp_dot_v1_dot_core__pb2.ListRootsResponse.SerializeToString,
            ),
            'WatchRoots': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchRoots,
                    request_deserializer=macp_dot_v1_dot_core__pb2.WatchRootsRequest.FromString,
                    response_serializer=macp_dot_v1_dot_core__pb2.WatchRootsResponse.SerializeToString,
            ),
            'ListExtModes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExtModes,
                    request_deserializer=macp_dot_v1_dot_core__pb2.ListExtModesRequest.FromString,
                    response_serializer=macp_dot_v1_dot_core__pb2.ListExtModesResponse.SerializeToString,
            ),
            'RegisterExtMode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterExtMode,
                    request_deserializer=macp_dot_v1_dot_core__pb2.RegisterExtModeRequest.FromString,
                    response_serializer=macp_dot_v1_dot_core__pb2.RegisterExtModeResponse.SerializeToString,
            ),
            'UnregisterExtMode': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterExtMode,
                    request_deserializer=macp_dot_v1_dot_core__pb2.UnregisterExtModeRequest.FromString,
                    response_serializer=macp_dot_v1_dot_core__pb2.UnregisterExtModeResponse.SerializeToString,
            ),
            'PromoteMode': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteMode,
                    request_deserializer=macp_dot_v1_dot_core__pb2.PromoteModeRequest.FromString,
                    response_serializer=macp_dot_v1_dot_core__pb2.PromoteModeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'macp.v1.MACPRuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('macp.v1.MACPRuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MACPRuntimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macp.v1.MACPRuntimeService/Initialize',
            macp_dot_v1_dot_core__pb2.InitializeRequest.SerializeToString,
            macp_dot_v1_dot_core__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macp.v1.MACPRuntimeService/Send',
            macp_dot_v1_dot_core__pb2.SendRequest.SerializeToString,
            macp_dot_v1_dot_core__pb2.SendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/macp.v1.MACPRuntimeService/StreamSession',
            macp_dot_v1_dot_core__pb2.StreamSessionRequest.SerializeToString,
            macp_dot_v1_dot_core__pb2.StreamSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macp.v1.MACPRuntimeService/GetSession',
            macp_dot_v1_dot_core__pb2.GetSessionRequest.SerializeToString,
            macp_dot_v1_dot_core__pb2.GetSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macp.v1.MACPRuntimeService/CancelSession',
            macp_dot_v1_dot_core__pb2.CancelSessionRequest.SerializeToString,
            macp_dot_v1_dot_core__pb2.CancelSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macp.v1.MACPRuntimeService/GetManifest',
            macp_dot_v1_dot_core__pb2.GetManifestRequest.SerializeToString,
            macp_dot_v1_dot_core__pb2.GetManifestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macp.v1.MACPRuntimeService/ListModes',
            macp_dot_v1_dot_core__pb2.ListModesRequest.SerializeToString,
            macp_dot_v1_dot_core__pb2.ListModesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchModeRegistry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/macp.v1.MACPRuntimeService/WatchModeRegistry',
            macp_dot_v1_dot_core__pb2.WatchModeRegistryRequest.SerializeToString,
            macp_dot_v1_dot_core__pb2.WatchModeRegistryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRoots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macp.v1.MACPRuntimeService/ListRoots',
            macp_dot_v1_dot_core__pb2.ListRootsRequest.SerializeToString,
            macp_dot_v1_dot_core__pb2.ListRootsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchRoots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/macp.v1.MACPRuntimeService/WatchRoots',
            macp_dot_v1_dot_core__pb2.WatchRootsRequest.SerializeToString,
            macp_dot_v1_dot_core__pb2.WatchRootsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListExtModes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macp.v1.MACPRuntimeService/ListExtModes',
            macp_dot_v1_dot_core__pb2.ListExtModesRequest.SerializeToString,
            macp_dot_v1_dot_core__pb2.ListExtModesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterExtMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macp.v1.MACPRuntimeService/RegisterExtMode',
            macp_dot_v1_dot_core__pb2.RegisterExtModeRequest.SerializeToString,
            macp_dot_v1_dot_core__pb2.RegisterExtModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterExtMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macp.v1.MACPRuntimeService/UnregisterExtMode',
            macp_dot_v1_dot_core__pb2.UnregisterExtModeRequest.SerializeToString,
            macp_dot_v1_dot_core__pb2.UnregisterExtModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/macp.v1.MACPRuntimeService/PromoteMode',
            macp_dot_v1_dot_core__pb2.PromoteModeRequest.SerializeToString,
            macp_dot_v1_dot_core__pb2.PromoteModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
