# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: macp/v1/envelope.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'macp/v1/envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16macp/v1/envelope.proto\x12\x07macp.v1\"\xa8\x01\n\x08\x45nvelope\x12\x14\n\x0cmacp_version\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\x14\n\x0cmessage_type\x18\x03 \x01(\t\x12\x12\n\nmessage_id\x18\x04 \x01(\t\x12\x12\n\nsession_id\x18\x05 \x01(\t\x12\x0e\n\x06sender\x18\x06 \x01(\t\x12\x19\n\x11timestamp_unix_ms\x18\x07 \x01(\x03\x12\x0f\n\x07payload\x18\x08 \x01(\x0c\"c\n\tMACPError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x12\n\nmessage_id\x18\x04 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x05 \x01(\x0c\"\xba\x01\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x11\n\tduplicate\x18\x02 \x01(\x08\x12\x12\n\nmessage_id\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t\x12\x1b\n\x13\x61\x63\x63\x65pted_at_unix_ms\x18\x05 \x01(\x03\x12,\n\rsession_state\x18\x06 \x01(\x0e\x32\x15.macp.v1.SessionState\x12!\n\x05\x65rror\x18\x07 \x01(\x0b\x32\x12.macp.v1.MACPError*|\n\x0cSessionState\x12\x1d\n\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12\x16\n\x12SESSION_STATE_OPEN\x10\x01\x12\x1a\n\x16SESSION_STATE_RESOLVED\x10\x02\x12\x19\n\x15SESSION_STATE_EXPIRED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'macp.v1.envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSIONSTATE']._serialized_start=496
  _globals['_SESSIONSTATE']._serialized_end=620
  _globals['_ENVELOPE']._serialized_start=36
  _globals['_ENVELOPE']._serialized_end=204
  _globals['_MACPERROR']._serialized_start=206
  _globals['_MACPERROR']._serialized_end=305
  _globals['_ACK']._serialized_start=308
  _globals['_ACK']._serialized_end=494
# @@protoc_insertion_point(module_scope)
