# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: macp/modes/task/v1/task.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'macp/modes/task/v1/task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dmacp/modes/task/v1/task.proto\x12\x12macp.modes.task.v1\"\x8f\x01\n\x12TaskRequestPayload\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x14\n\x0cinstructions\x18\x03 \x01(\t\x12\x1a\n\x12requested_assignee\x18\x04 \x01(\t\x12\r\n\x05input\x18\x05 \x01(\x0c\x12\x18\n\x10\x64\x65\x61\x64line_unix_ms\x18\x06 \x01(\x03\"F\n\x11TaskAcceptPayload\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08\x61ssignee\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\"F\n\x11TaskRejectPayload\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08\x61ssignee\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\"o\n\x11TaskUpdatePayload\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x10\n\x08progress\x18\x03 \x01(\x01\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x16\n\x0epartial_output\x18\x05 \x01(\x0c\"Y\n\x13TaskCompletePayload\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08\x61ssignee\x18\x02 \x01(\t\x12\x0e\n\x06output\x18\x03 \x01(\x0c\x12\x0f\n\x07summary\x18\x04 \x01(\t\"k\n\x0fTaskFailPayload\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x10\n\x08\x61ssignee\x18\x02 \x01(\t\x12\x12\n\nerror_code\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t\x12\x11\n\tretryable\x18\x05 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'macp.modes.task.v1.task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUESTPAYLOAD']._serialized_start=54
  _globals['_TASKREQUESTPAYLOAD']._serialized_end=197
  _globals['_TASKACCEPTPAYLOAD']._serialized_start=199
  _globals['_TASKACCEPTPAYLOAD']._serialized_end=269
  _globals['_TASKREJECTPAYLOAD']._serialized_start=271
  _globals['_TASKREJECTPAYLOAD']._serialized_end=341
  _globals['_TASKUPDATEPAYLOAD']._serialized_start=343
  _globals['_TASKUPDATEPAYLOAD']._serialized_end=454
  _globals['_TASKCOMPLETEPAYLOAD']._serialized_start=456
  _globals['_TASKCOMPLETEPAYLOAD']._serialized_end=545
  _globals['_TASKFAILPAYLOAD']._serialized_start=547
  _globals['_TASKFAILPAYLOAD']._serialized_end=654
# @@protoc_insertion_point(module_scope)
